[build]
  # Since this is a static HTML/CSS/JS site, no build process needed
  publish = "."
  
[build.environment]
  # Node.js version (if needed for any build tools)
  NODE_VERSION = "18"

[[headers]]
  # Apply security headers to all pages
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; img-src 'self' data:; font-src 'self' https://cdnjs.cloudflare.com; connect-src 'self' wss: ws:;"

[[headers]]
  # Cache static assets
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  # Cache images and videos
  for = "/*.{jpg,jpeg,png,gif,ico,svg,mp4,webm}"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  # Cache CSS and JS files
  for = "/*.{css,js}"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[redirects]]
  # Handle single page application routing
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  # Directory for serverless functions (if needed in future)
  directory = "netlify/functions"